2주차_김선화
dsc-sookmyung/2023-02-Flutter-Study pull request #8
Opened 2023-11-13 11:22 UTC by sunhwaaRj

2023-11-14 09:16 UTC, Jjinyshin requested changes
이번 주도 수고하셨습니다 :) 티스토리 팀 블로그도 확인 부탁드려요!

2023-11-14 09:16 UTC, Jjinyshin commented on README.md
> +| 1주차 | Dart 언어 이해하기        | <ul><li>- [ ] </li></ul> |
공용 README 파일은 수정하지 마시길 부탁드립니다!

2023-11-14 09:16 UTC, Jjinyshin commented on 김선화/week02/README.md
> +오늘 실행 코드~
앞으로 스터디를 진행하면서 하나의 앱을 만들어나갈 것이므로, 플러터 애플리케이션을 새로 생성하셔서 작업해주시고 그 변경사항을 PR로 보내주세요!
헷갈리신다면 이번 주차 @hanjeonghyun 님이 보내신 PR의 폴더 구조 참고해주세요!

2023-11-16 02:19 UTC, sunhwaaRj commented
플러터 파일 pr 합니다! 해당 이름/week 폴더 안에서 작업을 하면 오류가 떠서 다른 로컬 폴더에서 진행하고 main.dart 파일만 업로드 하였습니다 확인 부탁드립니다

2023-11-16 08:16 UTC, Jjinyshin commented
> 플러터 파일 pr 합니다! 해당 이름/week 폴더 안에서 작업을 하면 오류가 떠서 다른 로컬 폴더에서 진행하고 main.dart 파일만 업로드 하였습니다 확인 부탁드립니다

- 넵 이번주는 이렇게 하도록 하겠습니다! 다음 주부터는 프로젝트를 week폴더에서 만드시면 돼요!

2023-11-16 08:17 UTC, Jjinyshin approved these changes

2023-11-20 12:47 UTC, closed without merging